

def print_welcome():
	print("=" * 70)
	print("Welcome to my Call of War - Battle Simulator!!!")
	print("=" * 70)
	print()
	print("This tool lets you recreate and explore different")
	print()
	print("battle scenerios, all from the comfort of your terminal")
	print()
	print("and without any waiting!")
	print("\n" * 2)
	print("If you like what you see, please give the repo a star!")
	print("\n" * 1)
	print("-" * 70)
	print()
	print("Right now, you can only play with Axis units")
	print()
	print("> > > Please refer to tutorial.py for more detailed instructions < < <")
	print()
	print("-" * 70)
	print("\n" * 2)
	print("*" * 70)
	print("This was a solo project by Daniel Proano, a Computer Science")
	print()
	print("student at Purdue University. If you really liked it")
	print()
	print("and want to support me, I'm looking for an internship!")
	print("\n" * 3)
	print("My LinkedIn: https://www.linkedin.com/in/daniel-proano-20976b32a/")
	print()
	print("My email: djz.labz@gmail.com")
	print("*" * 70)

if __name__ == "__main__":
	print_welcome()
